version: 0.2
phases:
 install:
  runtime-versions:
   nodejs: 12
  commands:
   
 pre_build:
  commands:
   - echo "Installing dependencies..."
   - npm install
   - npm install -g @angular/cli@12.2.6
 build:
  commands:
   - echo "Building Submission project..."   
   - ng build   
 post_build:
  commands:
  - ls -d $PWD/*
  
artifacts:
  files:
   - '**/*'
  discard-paths: no
