version: 0.2
env:
  variables:
    APP_NAME: "goa-test-app"
phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      - echo "Install process started for $ENV_EXAMPLEVAR..."
      - npm install && npm install -g @angular/cli
  build:
    commands:
      - echo "Build process started..."
      - ng build --configuration=production
  post_build:
    commands:
      - echo "Build process finished for $ENV_STAGE:$ENV_VERSION, uploading to S3"
      - cd dist/$APP_NAME
      - ls -la
      - aws s3 sync . s3://elverado-test --delete
